stages:
  - build
  - package
  - deploy

# Étape de build : compiler le projet Angular
build:
  stage: build
  image: node:16
  script:
    - npm install # Installer les dépendances
    - npm run build -- --prod # Construire l'application pour la production
  artifacts:
    paths:
      - dist/ # Sauvegarder le dossier dist pour la suite
# Étape de packaging : créer un fichier .tar.gz de l'application construite
package:
  stage: package
  script:
    - tar -czvf my-angular-app-${CI_COMMIT_REF_NAME}.tar.gz -C dist/ my-app # Créer un fichier d'archive
  artifacts:
    paths:
      - my-angular-app-${CI_COMMIT_REF_NAME}.tar.gz # Sauvegarder l'artefact pour un usage ultérieur
# Étape de déploiement (hypothétique, pour illustrer l'ensemble du pipeline)
deploy:
  stage: deploy
  script:
    - echo "Déploiement en cours..." # Ce serait la commande pour déployer sur un serveur ou un cloud
